name: elementary_cli
description: CLI utilities for Elementary
version: 1.0.0

executables:
  elementary_tools:

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  path: ^1.8.0
  args: ^2.3.0

dev_dependencies:
  lints: ^1.0.0
